---
- name: create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus.user_id }}"
  with_items:
   - "{{ prometheus.conf_dir }}"
   - "{{ prometheus.data_dir }}"

- name: write prometheus config file
  template:
    src: prometheus.yml
    dest: "{{ prometheus.conf_dir }}/"
    owner: "{{ prometheus.user_id }}"
  notify: service handler

- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
  with_items:
   - "{{ alertmanager.conf_dir }}"
   - "{{ alertmanager.data_dir }}"

- name: write alertmanager config file
  template:
    src: alertmanager.yml
    dest: "{{ alertmanager.conf_dir }}/"
    owner: "root"
  notify: service handler

- name: include setup_container.yml
  include_tasks: setup_container.yml
