---
grafana:
  admin_user: admin
  admin_password: admin
  # We only need this for SSL (https) connections
  crt: ''
  key: ''
  container_image: "grafana/grafana:latest"
  container_cpu_period: 100000
  container_cpu_cores: 2
  # container_memory is in GB
  container_memory: 4
  uid: 472
  datasource: Dashboard
  dashboards_path: "/etc/grafana/dashboards/ceph-dashboard"
  plugins:
    - vonage-status-panel
    - grafana-piechart-panel
